core/urls.py
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import HomePageView, WelcomePageView, MyCoursesPageView, CompletedCoursesPageView, CoursePageView, \
    get_week_dates

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('appointments/', include('appointments.urls')),
    path('chats/', include('chats.urls')),
    path('subjects/', include('subjects.urls')),
    path('schedule/', include('schedule.urls')),
    path('news/', include('news.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', WelcomePageView.as_view(), name='welcome'),
    path('home/', HomePageView.as_view(), name='home'),
    path('my-courses/', MyCoursesPageView.as_view(), name='my-courses'),
    path('completed-courses/', CompletedCoursesPageView.as_view(), name='completed-courses'),

    path('api/week-dates/', get_week_dates, name='week_dates'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/urls.py
from django.urls import path, re_path
from .views import (
    CourseListView, CourseDetailView, LessonCreateView,
    ModuleDetailView, LessonDetailView,
    CreateCourseStep1View, CreateCourseStep2View, CreateOrEditTestView, ModuleCreateView, AddStudentsView,
    add_student_to_course, TakeTestView, test_result_view, search_students, EditCourseView, CourseDelete,
    delete_literature, CourseFinalTestView, SuccessVideoLinkEditView, bulk_create_lessons, CourseModulesView,
    ModuleCreateViewAPI, LessonCreateViewAPI, LiteratureCreateViewAPI, LiteratureDeleteViewAPI, CreateCourseStep3View,
    CreateCourseStep4View, CreateCourseStep5View, CreateCourseEndingView, student_results_view, publishCourse,
    student_test_results_view, HomeworkCreateViewAPI, HomeworkDetailView, LiteratureDetailView, HomeworkDeleteViewAPI,
    UploadLiteratureView, StudentHomeworkUploadView
)
from core.views import CoursePageView, CourseStudentLecturePageView, course_redirect, CourseStudentTestPageView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='course_list'),
    path('<int:pk>/', CoursePageView.as_view(), name='course_detail'),
    path('student/<int:pk>/', course_redirect, name='course_start'),
    path('student/<int:pk>/<int:module_id>/<int:lesson_id>/lecture', CourseStudentLecturePageView.as_view(), name='course_student_lecture'),
    path('student/<int:pk>/<int:module_id>/<int:lesson_id>/test', CourseStudentTestPageView.as_view(), name='course_student_test_lesson'),
    path('student/<int:pk>/<int:module_id>/test', CourseStudentTestPageView.as_view(), name='course_student_test_module'),
    path('student/<int:pk>/test', CourseStudentTestPageView.as_view(), name='course_student_test_course'),
    path('edit/<int:pk>/', CourseDetailView.as_view(), name='course_detail_edit'),
    path('publish/<int:pk>/', publishCourse, name='course_publish'),
    path('edit/<int:pk>/about/', EditCourseView.as_view(), name='course_detail_edit_about'),
    path('delete/<int:pk>/', CourseDelete.as_view(), name='course_delete'),
    path('create/step1/', CreateCourseStep1View.as_view(), name='create_course_step1'),
    path('create/step2/', CreateCourseStep2View.as_view(), name='create_course_step2'),
    path('create/step3/<int:course_id>', CreateCourseStep3View.as_view(), name='create_course_step3'),
    path('create/step4/<int:course_id>', CreateCourseStep4View.as_view(), name='create_course_step4'),
    path('create/step5/<int:course_id>', CreateCourseStep5View.as_view(), name='create_course_step5'),
    path('create/ending/<int:course_id>', CreateCourseEndingView.as_view(), name='create_course_ending'),
    path('<int:course_id>/module/create/', ModuleCreateViewAPI.as_view(), name='module_create'),
    path('<int:module_id>/lesson/create/', LessonCreateViewAPI.as_view(), name='lesson_create'),

    path('literature/create/<int:lesson_id>/', LiteratureCreateViewAPI.as_view(), name='literature-create'),
    path('literature/delete/<int:literature_id>/', LiteratureDeleteViewAPI.as_view(), name='literature-delete'),

    path('<int:lesson_id>/homework/create/', HomeworkCreateViewAPI.as_view(), name='homework_create'),

    path('<int:course_id>/<int:module_id>/<int:pk>/homework/', HomeworkDetailView.as_view(),
                       name='course_student_homework'),

    path('student/<int:course_id>/<int:module_id>/<int:lesson_id>/literature/',
                       LiteratureDetailView.as_view(), name='course_student_literature'),

    path('homework/<int:homework_id>/delete/', HomeworkDeleteViewAPI.as_view(), name='homework-delete'),

    path('module/<int:pk>/', ModuleDetailView.as_view(), name='module_detail'),
    path('<int:pk>/final_test/edit', CourseFinalTestView.as_view(), name='final_test_creation'),
    path('<int:pk>/success_video/edit', SuccessVideoLinkEditView.as_view(), name='success_video_edit'),
    path('lesson/<int:pk>/', LessonDetailView.as_view(), name='lesson_detail'),
    path('<str:parent_type>/<int:parent_id>/test/', CreateOrEditTestView.as_view(), name='create_edit_test'),
    path('course/<int:pk>/add-students/', AddStudentsView.as_view(), name='add_students'),
    path('<int:course_id>/add-student/<int:student_id>/', add_student_to_course, name='add_student_to_course'),
    path('course/search-students/', search_students, name='search_students'),

    path('<int:course_id>/student/<str:student_login_code>', student_results_view, name='student_results'),
    path('<int:course_id>/student/<str:student_login_code>/<int:submission_id>', student_test_results_view, name='student_test_results'),

    path('test/take/<int:course_id>/<int:module_id>/<int:lesson_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_lesson'),
    path('test/take/<int:course_id>/<int:module_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_module'),
    path('test/take/<int:course_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_course'),
    re_path(r'^test/result/(?P<score>\d+\.\d+)/$', test_result_view, name='test_result'),

    path('course/<int:course_id>/module/', ModuleDetailView.as_view(), name='module_detail'),
    path('module/<int:module_id>/bulk-create-lessons/', bulk_create_lessons, name='bulk_create_lessons'),
    path('module/<int:module_id>/update-module-and-lessons/', bulk_create_lessons, name='update_module_and_lessons'),
    path('<int:course_id>/modules/api/', CourseModulesView.as_view(), name='course-modules'),

    path('lessons/<int:lesson_id>/literature/upload/', UploadLiteratureView.as_view(),
                       name='upload-literature'),

    path('<int:course_id>/<int:module_id>/<int:lesson_id>/homework/upload/', StudentHomeworkUploadView.as_view(), name='student_homework_upload'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView, ShowCodeView, LoginView, GrantAccessView, ProfileView, CheckAccessView, log_out, \
    change_password, create_teacher, StudentCheckProfileView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('show_code/', ShowCodeView.as_view(), name='show_code'),  # Ensure this is correct
    path('grant-access/', GrantAccessView.as_view(), name='grant_access'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('check-access/', CheckAccessView.as_view(), name='check-access'),
    path('change-password/', change_password, name='change_password'),

    path('student/<int:pk>/profile/', StudentCheckProfileView.as_view(), name='student_check_profile'),

    path('create-teacher/', create_teacher, name='create-teacher'),
]

courses/forms.py
from django import forms
from .models import Course, Module, Lesson, LessonLiterature, Test, Question, Answer, Rating, Homework
from users.models import CustomUser

class CourseForm(forms.ModelForm):
    course_difficulty = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=Course.DIFFICULTY_CHOICES,
    )
    course_picture = forms.ImageField(required=False)

    class Meta:
        model = Course
        fields = ['course_name', 'mini_description', 'course_picture', 'big_description', 'course_time', 'course_difficulty', 'full_description']

class CourseFormStep1(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'mini_description', 'course_picture']

class CourseFormStep2(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['big_description', 'course_time', 'course_difficulty', 'full_description']

class ModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = ['module_name']

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['lesson_name', 'video_link']

class LessonLiteratureForm(forms.ModelForm):
    class Meta:
        model = LessonLiterature
        fields = ['literature_name', 'literature_type', 'file']

class HomeworkForm(forms.ModelForm):
    class Meta:
        model = Homework
        fields = ['homework_name', 'file']

class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['title']  # Include other relevant fields


class QuestionForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    audio = forms.FileField(required=False)

    class Meta:
        model = Question
        fields = ['text', 'question_type', 'image', 'audio']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'is_correct']

from django.core.validators import RegexValidator


# class AddStudentForm(forms.Form):
#     search_query = forms.CharField(
#         label='Search by name',
#         max_length=100,
#         required=False,
#         help_text='Enter the full name of the student.'
#     )
#     phone_number = forms.CharField(
#         label='Search by phone number',
#         max_length=15,
#         required=False,
#         help_text='Enter the phone number of the student.'
#     )
#     login_code = forms.CharField(
#         label='Search by login code',
#         max_length=7,
#         required=False,
#         help_text='Enter the login code of the student.'
#     )
#
#     def clean(self):
#         cleaned_data = super().clean()
#         search_query = cleaned_data.get('search_query')
#         phone_number = cleaned_data.get('phone_number')
#         login_code = cleaned_data.get('login_code')
#
#         if not any([search_query, phone_number, login_code]):
#             raise forms.ValidationError("Please provide at least one search criteria.")
#
#         if sum([bool(search_query), bool(phone_number), bool(login_code)]) > 1:
#             raise forms.ValidationError("Please search by only one criterion at a time.")
#
#         return cleaned_data

class AddStudentForm(forms.Form):
    login_code = forms.CharField(
        label='Search by login code',
        max_length=7,
        required=False,
        help_text='Enter the login code of the student.'
    )

    def clean(self):
        cleaned_data = super().clean()
        login_code = cleaned_data.get('login_code')

        if not login_code:
            raise forms.ValidationError("Please provide the login code.")

        return cleaned_data


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['rating']


class SuccessVideoLinkForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_success_video']

courses/templates/courses/course/add_students.html
{% extends 'core/base.html' %}

{% block content %}
<h2>Add Students to Course</h2>
<form method="get" action="{% url 'courses:add_students' pk=course.pk %}">
    {{ form.as_p }}
    <button type="submit">Search</button>
</form>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const loginCodeInput = document.querySelector('#id_login_code');

    loginCodeInput.addEventListener('input', function () {
        let value = loginCodeInput.value.replace(/[^0-9]/g, '');
        if (value.length > 3) {
            value = value.substring(0, 3) + '-' + value.substring(3);
        }
        loginCodeInput.value = value;
    });
});
</script>

<hr>
{% if students %}
    <ul>
    {% for student in students %}
        <li>
            {{ student.full_name }}
            {% if student.enrolled %}
                - <a href="{% url 'courses:remove_student_from_course' course_id=course.pk student_id=student.id %}">Remove from Course</a>
            {% else %}
                - <a href="{% url 'courses:add_student_to_course' course_id=course.pk student_id=student.id %}">Add to Course</a>
            {% endif %}
        </li>
    {% empty %}
        <li>No students found.</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No search performed yet or no results found.</p>
{% endif %}

{% if can_add_students %}
    <a href="{% url 'courses:add_students' pk=course.pk %}" class="btn btn-primary">Add More Students</a>
{% endif %}
{% endblock %}

courses/templates/courses/course/course_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load course_tags %}

{% block title %}{{ course.course_name }}{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include "core/components/navbar-main-without-links.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div class="container content bg-no-repeat bg-top mx-auto font-[Qanelas] text-black-main pt-14">
        <h1 class="text-[42px] font-bold mb-3">Редактирование курса</h1>
        <div class="white-block p-14 mb-5">
            <h2 class="text-[32px] font-semibold">Добавить ученика по ID</h2>
            <form id="searchForm" method="get" action="{% url 'courses:search_students' %}">
                <div class="relative mb-3">
                    <input type="text" name="login_code" id="id_login_code"
                           class="peer focus:outline-none w-full placeholder-black-main py-6 px-8 border border-gray rounded-lg"
                           placeholder="Добавить ученика по ID" required>
                    <img class="absolute inset-y-1/2 -translate-y-1/2 right-6 peer-focus-hidden border-transparent focus:border-transparent focus:ring-0"
                         src="{% static 'core/icons/search-accent-red.svg' %}" alt="">
                    <button class="absolute inset-y-2 right-2 text-center
                    rounded-lg bg-accent-red text-white text-lg font-semibold
                    hidden w-[189px] h-full-4 peer-focus-inline-block peer-valid-inline-block z-10" type="submit">Поиск
                    </button>
                </div>
            </form>
            <div id="searchResults" class="flex flex-col gap-3">

            </div>

        </div>
        <div class="bg-no-repeat bg-cover bg-center py-[60px] rounded-xl flex flex-col items-center mb-5"
             style="background-image: url('{% static "core/images/gasyr-accent-red-background.png" %}')">
            <h2 class="text-white text-2xl font-bold mb-[30px] uppercase tracking-widest">Предпросмотр карточки</h2>
            <div class="max-w-[650px] mb-[51px]">
                {% include "core/components/course-card-start.html" with course=course %}
            </div>
            <div class="grid grid-cols-2 gap-3 text-accent-red text-center text-xl font-semibold *:w-[391px] *:bg-white *:py-[26px] *:rounded-lg">
                <a href="{% url 'courses:course_detail_edit_about' pk=course.id %}">Изменить информацию о курсе</a>
                <a href="{% url 'courses:final_test_creation' pk=course.id %}">Редактировать финальный тест</a>
                {% if course.modules.count > 0 %}
                    <a href="{% url 'courses:module_detail' pk=course.modules.all.0.id %}">Редактировать модули</a>
                {% else %}
                    <a href="{% url 'courses:module_create' course_id=course.id %}">Добавить модули</a>
                {% endif %}
                <a href="{% url 'courses:success_video_edit' pk=course.id %}">Поменять видео-поздравление</a>
            </div>
            <a class="text-accent-red text-center text-xl font-semibold w-[391px] bg-white py-[26px] rounded-lg mt-[52px]"
               href="{% url 'courses:course_publish' pk=course.id %}">{% if course.published %}Убрать в черновики{% else %}Опубликовать курс{% endif %}</a>
        </div>
        <div class="bg-white p-14 rounded-lg mb-36">
            <h2 class="text-[32px] font-semibold pb-[13px]">Ученики</h2>
            <div class="flex flex-col gap-3">
                {% comment %} <div class="w-full p-2.5 pr-6 border border-[#CDCDCD] rounded-lg flex flex-row items-center text-xl">
                </div> {% endcomment %}
                <form >
                    <div class="relative mb-3">
                        <input type="text" name="login_code" id="id_login_code"
                               class="peer focus:outline-none w-full placeholder-black-main py-6 px-8 border border-gray rounded-lg"
                               placeholder="Добавить ученика по ID" required>
                        <img class="absolute inset-y-1/2 -translate-y-1/2 right-6 peer-focus-hidden border-transparent focus:border-transparent focus:ring-0"
                             src="{% static 'core/icons/search-accent-red.svg' %}" alt="">
                        <button class="absolute inset-y-2 right-2 text-center rounded-lg bg-accent-red text-white text-lg font-semibold hidden w-[189px] h-full-4 peer-focus-inline-block peer-valid-inline-block z-10" type="submit">
                            Поиск
                        </button>
                    </div>
                </form>
                
                {% for student in students %}
                    <div class="flex flex-row items-center justify-between w-full p-2.5 pr-6 border border-[#CDCDCD] rounded-lg  text-xl">
                        <div class="flex flex-row gap-6 pr-20 items-center">
                            <img class="w-[60px] h-[60px] object-cover rounded-full mr-6"
                             src="{% if student.profile_picture %}
                                {{ student.profile_picture.url }}
                                {% else %}
                                {% static "core/images/anonymous-user-image.png" %}
                                {% endif %}" alt='Ava'>
                            <p class=" text-xl font-medium text-[#4F4F4F]">{{ student.full_name }}</p>
                        </div>
                        
                        <p class="text-xl font-medium text-black">{{ student.phone_number|format_phone_number }}</p>
                        <!-- Change Date to Данные -->
                        <a class="text-xl font-medium text-black" href="{% url 'users:student_check_profile' pk=student.id %}" class="text-blue-ielts underline">Данные</a>
                        <p class="text-xl font-medium text-black">{{ student.login_code }}</p>
                        <a href="{% url 'courses:student_results' course_id=course.id student_login_code=student.login_code %}" class="text-blue-ielts underline">Результаты</a>
                    </div>
                {% empty %}
                    <div class="bg-white p-[50px] rounded-lg text-center">
                        <img class="mx-auto mb-6" src="{% static "core/images/cats/student.png" %}">
                        <p class="text-2xl font-bold ">Тут пока никого нет :(</p>
                    </div>
                {% endfor %}
            </div>        
        </div>
    </div>
















    <script>
        $(document).ready(function () {
            $('#searchForm').submit(function (event) {
                event.preventDefault(); // Prevent the form from submitting through the browser.
                var formData = $(this).serialize(); // Serialize the form data.

                $.ajax({
                    url: "{% url 'courses:search_students' %}",
                    type: 'get',
                    data: formData,
                    success: function (data) {
                        // Update the search results div with new HTML from the server
                        $('#searchResults').html(data);
                    },
                    error: function () {
                        alert('Error loading search results.');
                    }
                });
            });
        });
    </script>

    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        function enrollStudent(studentId) {
            console.log("Student ID:", studentId, "Course ID:", {{ course.id }});  // This will show the values in the browser console

            const csrftoken = getCookie('csrftoken');  // Get the CSRF token from the cookie

            fetch(`/courses/{{ course.id }}/add-student/${studentId}/`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken  // Include CSRF token in the request header
                }
            })
                .then(response => response.json())
                .then(data => {
                    document.getElementById('message-cat').src = "{% static 'core/images/cats/student-sit.png' %}"
                    document.getElementById('message-title').innerText = "Ученик добавлен"
                    document.getElementById('message-text').innerText = "Вы можете наблюдать за ним, во вкладке “Ученики”"
                    document.getElementById('accessMessage').classList.remove("hidden");
                })
                .catch(error => {
                    console.error('Error adding student:', error);
                    document.getElementById('message-cat').src = "{% static 'core/images/cats/student-sit.png' %}"
                    document.getElementById('message-title').innerText = "Ошибка добавления студента"
                    document.getElementById('message-text').innerText = "Убедитесь что это студент (учителей добавлять нельзя)"
                    document.getElementById('accessMessage').classList.remove("hidden");
                });
        }

    </script>
{% endblock %}

courses/templates/courses/course/course_list.html
{% extends 'core/base.html' %}
{% block content %}
<style>
    button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        margin: 5px;
    }
    #courseList {
        border: 1px solid #ddd;
        padding: 10px;
        border-radius: 5px;
        background-color: #f9f9f9;
    }
    h1 {
        color: #333;
    }
</style>

<h1>Courses</h1>
<button id="allCourses">All Courses</button>
<button id="myCourses">My Courses</button>
<button id="endedCourses">Ended Courses</button>
<div id="courseList">
    {% include 'courses/_course_list_partial.html' %}
</div>

<script>
    function fetchCourses(dataType) {
    const url = "{% url 'courses:course_list' %}";
    const data = {
        'data_type': dataType,
        'csrfmiddlewaretoken': '{{ csrf_token }}'
    };
    fetch(url, {
        method: 'POST',
        headers: {
            'X-Requested-With': 'XMLHttpRequest',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: new URLSearchParams(data)
    })
    .then(response => response.json())
    .then(data => {
        document.getElementById('courseList').innerHTML = data.html;
    })
    .catch(error => console.error('Error:', error));
}

    document.getElementById('allCourses').addEventListener('click', () => fetchCourses('all'));
    document.getElementById('myCourses').addEventListener('click', () => fetchCourses('mine'));
document.getElementById('endedCourses').addEventListener('click', () => fetchCourses('ended'));
</script>

{% endblock %}

courses/templates/courses/course/create_course_ending.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ course.course_name }}{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include "core/components/navbar-main-without-links.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div class="container content bg-no-repeat bg-top mx-auto font-[Qanelas] text-black-main pt-14">

        <div class="white-block mb-[50px]  overflow-y-auto">
            <div class="px-[230px] pt-[30px] text-center">
                <img class="inline-block mb-[30px]" src="{% static 'core/images/cats/box.png' %}" alt="">
                <h2 class="text-[32px] font-bold mb-[10px]">Теперь, мы вас поздравляем!</h2>
                <p class="text-lg mb-[30px]">
                    Курс уже загружен и ждет учеников
                </p>
                <a class="w-[390px] text-center mb-[30px] py-[26px] border border-accent-red text-accent-red text-xl font-semibold rounded-lg mx-auto block"
                   href="{% url 'courses:course_detail_edit' pk=course.id %}">Вернуться на главную
                </a>
            </div>
        </div>
    </div>
{% endblock %}

courses/templates/courses/course/create_course_step3.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ course.course_name }}{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include "core/components/navbar-main-without-links.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div class="container content bg-no-repeat bg-top mx-auto font-[Qanelas] text-black-main pt-14">
        {% include 'core/components/create-progress.html' with step=3 %}
        <form method="post">
            <h2 class="text-[42px] font-bold">Модули и уроки</h2>

            {% include 'core/components/courses-and-lessons-forms.html' with course=course create=True %}
            <div class="flex flex-row">
                <a class="w-[390px] text-center py-[26px] border border-gray text-gray text-xl font-semibold rounded-lg mx-auto block"
                   href="javascript:history.back()">Предыдущий этап
                </a>
                <button onclick="next()" type="button" class="block border border-accent-red text-accent-red text-xl
                font-semibold mx-auto py-[23px] w-[391px] rounded-lg">
                    Следующий этап
                </button>
            </div>
{#            <a href="{% url 'courses:course_detail_edit' pk=course.id %}" type="submit" class="block text-center border border-accent-red text-accent-red text-xl#}
{#                font-semibold mx-auto py-[23px] w-[391px] rounded-lg" id="confirmButton">#}
{#                Сохранить изменения#}
{#            </a>#}
        </form>
    </div>
    <script>
    async function next() {
        await send_data();
        window.location.replace("{% url 'courses:create_course_step4' course_id=course.id %}")
    }
    </script>
{% endblock %}


{% block onload_script %}
    getAllModules();
{% endblock %}

courses/templates/courses/course/create_course_step4.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ course.course_name }}{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include "core/components/navbar-main-without-links.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div class="container content bg-no-repeat bg-top mx-auto font-[Qanelas] text-black-main pt-14">
        {% include 'core/components/create-progress.html' with step=4 %}

        {% include 'core/components/add-final-test.html' with course=course create=True %}
        <div class="flex flex-row">
            <a class="w-[390px] text-center py-[26px] border border-gray text-gray text-xl font-semibold rounded-lg mx-auto block"
               href="javascript:history.back()">Предыдущий этап
            </a>
            <a class="w-[390px] text-center py-[26px] border border-accent-red text-accent-red text-xl font-semibold rounded-lg mx-auto block"
               href="{% url 'courses:create_course_step5' course_id=course.id %}">Следующий этап
            </a>
        </div>
    </div>
{% endblock %}

courses/templates/courses/course/create_course_step5.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ course.course_name }}{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include "core/components/navbar-main-without-links.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div class="container content bg-no-repeat bg-top mx-auto font-[Qanelas] text-black-main pt-14">
        {% include 'core/components/create-progress.html' with step=5 %}

        {% include 'core/components/success-video-link.html' with course=course create=True %}
        <div class="flex flex-row">
            <a class="w-[390px] text-center py-[26px] border border-gray text-gray text-xl font-semibold rounded-lg mx-auto block"
               href="javascript:history.back()">Предыдущий этап
            </a>
            <a class="w-[390px] text-center py-[26px] border border-accent-red text-accent-red text-xl font-semibold rounded-lg mx-auto block"
               href="{% url 'courses:create_course_ending' course_id=course.id %}">Опубликовать курс
            </a>
        </div>
    </div>
{% endblock %}

courses/templates/courses/course/final-test-edit.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ course.course_name }}{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include "core/components/navbar-main-without-links.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div class="container content bg-no-repeat bg-top mx-auto font-[Qanelas] text-black-main pt-14">

        {% include 'core/components/add-final-test.html' with course=course %}
        <a href="{% url 'courses:course_detail_edit' pk=course.id %}" class="block text-center border border-accent-red text-accent-red text-xl
        font-semibold mx-auto py-[23px] w-[391px] rounded-lg">
            Сохранить изменения
        </a>
    </div>
{% endblock %}