core/urls.py
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import HomePageView, WelcomePageView, MyCoursesPageView, CompletedCoursesPageView, CoursePageView, \
    get_week_dates

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('appointments/', include('appointments.urls')),
    path('chats/', include('chats.urls')),
    path('subjects/', include('subjects.urls')),
    path('schedule/', include('schedule.urls')),
    path('news/', include('news.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', WelcomePageView.as_view(), name='welcome'),
    path('home/', HomePageView.as_view(), name='home'),
    path('my-courses/', MyCoursesPageView.as_view(), name='my-courses'),
    path('completed-courses/', CompletedCoursesPageView.as_view(), name='completed-courses'),

    path('api/week-dates/', get_week_dates, name='week_dates'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/urls.py
from django.urls import path, re_path
from .views import (
    CourseListView, CourseDetailView, LessonCreateView,
    ModuleDetailView, LessonDetailView,
    CreateCourseStep1View, CreateCourseStep2View, CreateOrEditTestView, ModuleCreateView, AddStudentsView,
    add_student_to_course, TakeTestView, test_result_view, search_students, EditCourseView, CourseDelete,
    delete_literature, CourseFinalTestView, SuccessVideoLinkEditView, bulk_create_lessons, CourseModulesView,
    ModuleCreateViewAPI, LessonCreateViewAPI, LiteratureCreateViewAPI, LiteratureDeleteViewAPI, CreateCourseStep3View,
    CreateCourseStep4View, CreateCourseStep5View, CreateCourseEndingView, student_results_view, publishCourse,
    student_test_results_view, HomeworkCreateViewAPI, HomeworkDetailView, LiteratureDetailView, HomeworkDeleteViewAPI,
    UploadLiteratureView, StudentHomeworkUploadView
)
from core.views import CoursePageView, CourseStudentLecturePageView, course_redirect, CourseStudentTestPageView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='course_list'),
    path('<int:pk>/', CoursePageView.as_view(), name='course_detail'),
    path('student/<int:pk>/', course_redirect, name='course_start'),
    path('student/<int:pk>/<int:module_id>/<int:lesson_id>/lecture', CourseStudentLecturePageView.as_view(), name='course_student_lecture'),
    path('student/<int:pk>/<int:module_id>/<int:lesson_id>/test', CourseStudentTestPageView.as_view(), name='course_student_test_lesson'),
    path('student/<int:pk>/<int:module_id>/test', CourseStudentTestPageView.as_view(), name='course_student_test_module'),
    path('student/<int:pk>/test', CourseStudentTestPageView.as_view(), name='course_student_test_course'),
    path('edit/<int:pk>/', CourseDetailView.as_view(), name='course_detail_edit'),
    path('publish/<int:pk>/', publishCourse, name='course_publish'),
    path('edit/<int:pk>/about/', EditCourseView.as_view(), name='course_detail_edit_about'),
    path('delete/<int:pk>/', CourseDelete.as_view(), name='course_delete'),
    path('create/step1/', CreateCourseStep1View.as_view(), name='create_course_step1'),
    path('create/step2/', CreateCourseStep2View.as_view(), name='create_course_step2'),
    path('create/step3/<int:course_id>', CreateCourseStep3View.as_view(), name='create_course_step3'),
    path('create/step4/<int:course_id>', CreateCourseStep4View.as_view(), name='create_course_step4'),
    path('create/step5/<int:course_id>', CreateCourseStep5View.as_view(), name='create_course_step5'),
    path('create/ending/<int:course_id>', CreateCourseEndingView.as_view(), name='create_course_ending'),
    path('<int:course_id>/module/create/', ModuleCreateViewAPI.as_view(), name='module_create'),
    path('<int:module_id>/lesson/create/', LessonCreateViewAPI.as_view(), name='lesson_create'),

    path('literature/create/<int:lesson_id>/', LiteratureCreateViewAPI.as_view(), name='literature-create'),
    path('literature/delete/<int:literature_id>/', LiteratureDeleteViewAPI.as_view(), name='literature-delete'),

    path('<int:lesson_id>/homework/create/', HomeworkCreateViewAPI.as_view(), name='homework_create'),

    path('<int:course_id>/<int:module_id>/<int:pk>/homework/', HomeworkDetailView.as_view(),
                       name='course_student_homework'),

    path('student/<int:course_id>/<int:module_id>/<int:lesson_id>/literature/',
                       LiteratureDetailView.as_view(), name='course_student_literature'),

    path('homework/<int:homework_id>/delete/', HomeworkDeleteViewAPI.as_view(), name='homework-delete'),

    path('module/<int:pk>/', ModuleDetailView.as_view(), name='module_detail'),
    path('<int:pk>/final_test/edit', CourseFinalTestView.as_view(), name='final_test_creation'),
    path('<int:pk>/success_video/edit', SuccessVideoLinkEditView.as_view(), name='success_video_edit'),
    path('lesson/<int:pk>/', LessonDetailView.as_view(), name='lesson_detail'),
    path('<str:parent_type>/<int:parent_id>/test/', CreateOrEditTestView.as_view(), name='create_edit_test'),
    path('course/<int:pk>/add-students/', AddStudentsView.as_view(), name='add_students'),
    path('<int:course_id>/add-student/<int:student_id>/', add_student_to_course, name='add_student_to_course'),
    path('course/search-students/', search_students, name='search_students'),

    path('<int:course_id>/student/<str:student_login_code>', student_results_view, name='student_results'),
    path('<int:course_id>/student/<str:student_login_code>/<int:submission_id>', student_test_results_view, name='student_test_results'),

    path('test/take/<int:course_id>/<int:module_id>/<int:lesson_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_lesson'),
    path('test/take/<int:course_id>/<int:module_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_module'),
    path('test/take/<int:course_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_course'),
    re_path(r'^test/result/(?P<score>\d+\.\d+)/$', test_result_view, name='test_result'),

    path('course/<int:course_id>/module/', ModuleDetailView.as_view(), name='module_detail'),
    path('module/<int:module_id>/bulk-create-lessons/', bulk_create_lessons, name='bulk_create_lessons'),
    path('module/<int:module_id>/update-module-and-lessons/', bulk_create_lessons, name='update_module_and_lessons'),
    path('<int:course_id>/modules/api/', CourseModulesView.as_view(), name='course-modules'),

    path('lessons/<int:lesson_id>/literature/upload/', UploadLiteratureView.as_view(),
                       name='upload-literature'),

    path('<int:course_id>/<int:module_id>/<int:lesson_id>/homework/upload/', StudentHomeworkUploadView.as_view(), name='student_homework_upload'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView, ShowCodeView, LoginView, GrantAccessView, ProfileView, CheckAccessView, log_out, \
    change_password, create_teacher, StudentCheckProfileView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('show_code/', ShowCodeView.as_view(), name='show_code'),  # Ensure this is correct
    path('grant-access/', GrantAccessView.as_view(), name='grant_access'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('check-access/', CheckAccessView.as_view(), name='check-access'),
    path('change-password/', change_password, name='change_password'),

    path('student/<int:pk>/profile/', StudentCheckProfileView.as_view(), name='student_check_profile'),

    path('create-teacher/', create_teacher, name='create-teacher'),
]

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "core/css/output.css" %}" rel="stylesheet">
    <style>
        @media screen and (min-width: 1120px) {
            body {
                zoom: 80%;
            }
        }
    </style>
</head>
<body class="{% block body-classes %}{% endblock %}">
    {% comment %}  {% endcomment %}
{% block content %}
    {% csrf_token %}
{% endblock %}
{% include "core/components/cookies.html" %}
{% include "core/components/message.html" %}
<script>
    window.onload = () => {
        cookiesOnLoad()
        {% if messages %}
        messagesOnLoad()
        {% endif %}
        {% block onload_script %}

        {% endblock %}
    }
</script>
</body>
</html>

core/templates/core/completed-courses.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Пройденные курсы{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include 'core/components/navbar-main.html' %}
    <div class="container px-5 content bg-no-repeat bg-top mx-auto font-[Qanelas] pt-[32px] md:pt-14 text-black-main">
        <h1 class="text-[24px] md:text-[42px] font-bold mb-3">Пройденные курсы</h1>
        {% if completed_courses %}
            <div class="grid grid-cols-1 md:grid-cols-2 gap-5 mb-10">
                {% for course in completed_courses %}
                {% include 'core/components/course-card-completed.html' with course=course %}
                {% endfor %}
            </div>
        {% else %}
            <div class="w-full text-center bg-white pb-32 pt-6">
                <img class="p-10 md:p-0 h-max-[302px] w-max-[296px] md:h-max-none md:w-max-none mx-auto mb-6" src="{% static "core/images/cats/no-completed-courses.png" %}" alt="">
                <h4 class="text-2xl font-semibold">Пройденных курсов, все еще нет :(</h4>
            </div>
        {% endif %}
    </div>
    {% csrf_token %}
    {% comment %}
<h2>Welcome to the Home Page</h2>
<p>This is your home page. Navigate through the site from here.</p>

{% if request.user.role == "Teacher" or request.user.is_superuser %}
HI TEQACHER/ADMIN
    <a href="{% url 'users:grant_access' %}">Give Access</a>

{% endif %}
{% endcomment %}

{% endblock %}

core/templates/core/course_detail.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}{{ course.course_name }}{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include 'core/components/navbar-main.html' %}
    <div class="container content bg-no-repeat px-5 bg-top mx-auto font-[Qanelas] pt-14 text-black-main">
        <div class="relative w-full rounded-lg h-[90px] md:h-80 bg-cover"
     style="background-image: url('{% if course.course_picture %}{{ course.course_picture.url }}{% else %}{% static "core/images/course-default-bg.png" %}{% endif %}')">

            <div class="hidden absolute bottom-5 left-5 rounded-lg bg-white py-3 px-4 md:flex flex-row items-center">
                <p class="mr-[35px] font-semibold">Сложность</p>
                <div class="inline-block relative">
                    <img src="{% static "core/icons/difficulty-empty.png" %}" alt="">
                    <div class="absolute top-0 overflow-hidden bg-no-repeat bg-cover h-3"
                         style="width: {% widthratio course.course_difficulty 1 20 %}%; background-image: url('{% static "core/icons/difficulty-filled.png" %}')">
                    </div>
                </div>
            </div>
        </div>
        <div class="flex flex-row">
            <div class="w-full md:w-2/3 md:p-10 mr-auto">
                <div class="md:hidden mt-4 rounded-lg bg-white py-3 px-4 w-fit flex flex-row items-center">
                    <p class="mr-[35px] font-semibold">Сложность</p>
                    <div class="inline-block relative">
                        <img src="{% static "core/icons/difficulty-empty.png" %}" alt="">
                        <div class="absolute top-0 overflow-hidden bg-no-repeat bg-cover h-3"
                             style="width: {% widthratio course.course_difficulty 1 20 %}%; background-image: url('{% static "core/icons/difficulty-filled.png" %}')">
                        </div>
                    </div>
                </div>
                <h1 class="font-bold text-2xl md:text-[42px] mb-4">{{ course.course_name }}</h1>
                <p class="font-light mb-9">{{ course.full_description }}</p>
                {# Modules #}
                {% for module in course.modules.all %}
                    <div class="flex flex-col gap-[8px] mb-8">
                        <div class="relative z-0 overflow-hidden">
                            <input type="checkbox" class="peer absolute inset-0 h-16 w-full z-10 opacity-0">
                            <div class="bg-white rounded-lg text-accent-red text-start px-3 md:px-6 py-5">
                                <span class="font-semibold">Модуль {{ forloop.counter }}: </span>
                                <span class="mr-auto">{{ module.module_name }}</span>
                            </div>
                            <img class="absolute right-6 top-4 accordion-red block"
                                 src="{% static "core/icons/arrow-right-button-accent-red.svg" %}" alt="">
                            <img class="absolute right-6 top-4 accordion-gray hidden"
                                 src="{% static "core/icons/arrow-down-button-gray.svg" %}" alt="">
                            <div class="overflow-hidden transition-all peer-active-max-h-full max-h-0">
                                <div class="md:px-6 md:py-3">
                                    <table class="w-full table-fixed">
                                        <tbody>
                                        {% for lesson in module.lessons.all %}
                                            <tr class="px-3 *:py-[20px] border-b border-[#D9D9D9]">
                                                <td class="w-2/12 font-bold">Урок {{ forloop.counter }}</td>
                                                <td>{{ lesson.lesson_name }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="md:hidden mb-4">
                    <div class="white-block">
                        <div class="border-b border-gray p-4 pb-6 flex flex-row items-center">
                            <img class="w-full max-w-14 rounded-full" src="{% if course.created_by.profile_picture %}
                                    /{{ course.created_by.profile_picture }}
                                    {% else %}
                                    {% static "core/images/default-user.svg" %}
                                {% endif %}" alt="">
                            <div class="ml-3.5 mr-8 h-fit">
                                <h2 class="text-[16px] text-black-main font-bold">{{ course.created_by.full_name }}</h2>
                                <p class="m-0">Учитель</p>
                            </div>
                        </div>
                        <div class="p-4">
                            <div class="py-6 px-5 w-full border border-gray rounded-lg text-accent-red text-base font-medium mb-2">
                                <img class="inline mr-5 align-text-top"
                                     src="{% static "core/icons/time-line-accent-red.svg" %}" alt="">
                                {{ course.course_time }} часов
                            </div>
                            <div class="py-6 px-5 w-full border border-gray rounded-lg text-accent-red text-basetext-lg font-medium mb-2">
                                <img class="inline mr-5 align-text-top"
                                     src="{% static "core/icons/book-open-line-accent-red.svg" %}" alt="">
                                {{ modules_count }} модулей
                            </div>
                            <div class="py-6 px-5 w-full border border-gray rounded-lg text-accent-red text-base font-medium mb-8">
                                <img class="inline mr-5 align-text-top"
                                     src="{% static "core/icons/pencil-line-accent-red.svg" %}" alt="">
                                {{ lessons_count }} уроков
                            </div>
                            <a href="{% if user in course.users.all %}{% url 'courses:course_start' pk=course.id %}{% else %}#{% endif %}" class="text-center block py-6 px-5 w-full bg-accent-red rounded-lg text-white text-lg font-medium mb-2">
                                {% if user in course.users.all %}Начать курс{% else %}Приобрести курс{% endif %}
                            </a>
                        </div>
                    </div>
                </div>

                {# About Teacher #}
                <div class="rounded-lg bg-white p-4 md:p-8 mb-[42px]">
                    <div class="flex flex-row items-center mb-5">
                        <img class="w-full max-w-14 rounded-full" src="{% if course.created_by.profile_picture %}
                                /{{ course.created_by.profile_picture }}
                                {% else %}
                                {% static "core/images/default-user.svg" %}
                            {% endif %}" alt="">
                        <div class="ml-3.5 mr-8 h-fit">
                            <h2 class="text-xl text-black-main font-bold">{{ course.created_by.full_name }}</h2>
                            <p class="m-0 font-light">Учитель</p>
                        </div>
                    </div>
                    <p class="font-light">
    {{ object.big_description }}
</p>
                </div>
                <a href="{% if user in course.users.all %}{% url 'courses:course_start' pk=course.id %}{% else %}#{% endif %}"
   class="py-6 px-5 w-full bg-accent-red rounded-lg text-white text-lg font-medium mb-2 max-w-[356px] block mx-auto text-center">
   {% if user in course.users.all %}Начать курс{% else %}Приобрести курс{% endif %}
</a>

            </div>


            <div class="hidden md:block w-1/3 relative">
                <div class="absolute left-0 -top-[35px] right-5 white-block">
                    <div class="border-b border-gray p-8 pb-6 flex flex-row items-center">
                        <img class="w-full max-w-14 rounded-full" src="{% if course.created_by.profile_picture %}
                                /{{ course.created_by.profile_picture }}
                                {% else %}
                                {% static "core/images/default-user.svg" %}
                            {% endif %}" alt="">
                        <div class="ml-3.5 mr-8 h-fit">
                            <h2 class="text-xl text-black-main font-bold">{{ course.created_by.full_name }}</h2>
                            <p class="m-0">Учитель</p>
                        </div>
                    </div>
                    <div class="p-8">
                        <div class="py-6 px-5 w-full border border-gray rounded-lg text-accent-red text-lg font-medium mb-2">
                            <img class="inline mr-5 align-text-top"
                                 src="{% static "core/icons/time-line-accent-red.svg" %}" alt="">
                            {{ course.course_time }} часов
                        </div>
                        <div class="py-6 px-5 w-full border border-gray rounded-lg text-accent-red text-lg font-medium mb-2">
                            <img class="inline mr-5 align-text-top"
                                 src="{% static "core/icons/book-open-line-accent-red.svg" %}" alt="">
                            {{ modules_count }} модулей
                        </div>
                        <div class="py-6 px-5 w-full border border-gray rounded-lg text-accent-red text-lg font-medium mb-8">
                            <img class="inline mr-5 align-text-top"
                                 src="{% static "core/icons/pencil-line-accent-red.svg" %}" alt="">
                            {{ lessons_count }} уроков
                        </div>
                        <a href="{% if user in course.users.all %}{% url 'courses:course_start' pk=course.id %}{% else %}#{% endif %}" class="text-center block py-6 px-5 w-full bg-accent-red rounded-lg text-white text-lg font-medium mb-2">
                            {% if user in course.users.all %}Начать курс{% else %}Приобрести курс{% endif %}
                        </a>
                    </div>
                </div>
            </div>


        </div>
        <h1 class="text-[24px] md:text-[42px] font-bold mt-7 md:mt-0 mb-3">Другие курсы</h1>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-5 mb-10">
            {% for course in courses %}
                {% include 'core/components/course-card-start.html' with course=course %}
            {% endfor %}

        </div>
    </div>
    {% csrf_token %}
{% endblock %}

core/templates/core/home.html
{% extends "core/base.html" %}
{% load static %}

{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include 'core/components/navbar-main-hello.html' %}
    <div class="container content bg-no-repeat bg-top mx-auto font-[Qanelas] pt-14 text-black-main">
        {% if user.is_authenticated %}
            <h1 class="text-[42px] font-bold mb-3">Продолжить обучение</h1>
            <div class="min-h-60 bg-cover bg-center rounded-lg p-8 text-white flex flex-row mb-12"
                 style="background-image: url('{% static "core/images/gasyr-red-row.png" %}')">
                <div class="p-3 text-start mr-auto">
                    <h4 class="text-2xl font-semibold">Вы остановились!</h4>
                    <h2 class="text-[32px] font-bold mb-[20px]">Курс по SAT:MATH для начинающих</h2>
                    <a class="inline-block text-white font-semibold py-5 px-16 border-white border-2 rounded-lg"
                       href="#">Продолжить курс</a>
                </div>
                <div class="relative h-full">
                    <svg class="w-[182px] h-[182px] m-auto z-0" viewBox="0 0 100 100">
                        <!-- Background circle -->
                        <circle
                                class="text-gray-200 stroke-white"
                                stroke-width="10"
                                cx="50"
                                cy="50"
                                r="40"
                                fill="transparent"
                        ></circle>
                        <!-- Progress circle -->
                        <circle
                                class="text-indigo-500 progress-ring__circle stroke-math"
                                stroke-width="10"
                                stroke-linecap="round"
                                cx="50"
                                cy="50"
                                r="40"
                                fill="transparent"
                                stroke-dasharray="251.2"
                                transform="rotate(90, 50, 50)"
                                stroke-dashoffset="calc(251.2 - (251.2 * 70) / 100)"
                        ></circle>
                    </svg>
                    <h2 class="absolute top-1/2 -translate-y-1/2 left-0 right-0 text-white text-[42px] font-bold leading-[58.8px] text-center">100%</h2>
                </div>
            </div>
            <h1 class="text-[42px] font-bold mb-3">Все курсы</h1>
        {% endif %}
        <div class="grid grid-cols-2 gap-5 mb-10">
            {% include 'core/components/course-card-start.html' %}
            {% include 'core/components/course-card-payed.html' %}
            {% include 'core/components/course-card-progress.html' %}
            {% include 'core/components/course-card-completed.html' %}
        </div>
    </div>
    {% csrf_token %}
    {% comment %}
<h2>Welcome to the Home Page</h2>
<p>This is your home page. Navigate through the site from here.</p>

{% if request.user.role == "Teacher" or request.user.is_superuser %}
HI TEQACHER/ADMIN
    <a href="{% url 'users:grant_access' %}">Give Access</a>

{% endif %}
{% endcomment %}

{% endblock %}

core/templates/core/my-courses.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Мои курсы{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include 'core/components/navbar-main.html' %}
    <div class="container px-5 content bg-no-repeat bg-top mx-auto font-[Qanelas] pt-10 text-black-main">
        <h1 class="text-[24px] md:text-[42px] font-bold mb-3">Мои курсы</h1>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-5 mb-10">
            {% for course in courses %}
                {% include 'core/components/course-card-start.html' with course=course %}
            {% endfor %}
        </div>
    </div>
    
    {% csrf_token %}
    {% comment %}
<h2>Welcome to the Home Page</h2>
<p>This is your home page. Navigate through the site from here.</p>

{% if request.user.role == "Teacher" or request.user.is_superuser %}
HI TEQACHER/ADMIN
    <a href="{% url 'users:grant_access' %}">Give Access</a>

{% endif %}
{% endcomment %}

{% endblock %}

core/templates/core/teacher-home.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Gasyr - foundation school{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include 'core/components/navbar-main-without-links.html' %}
    <div class="container content px-5 md:px-5 bg-no-repeat bg-top mx-auto font-[Qanelas] text-black-main">
        <div class="relative py-10">
            <div class="min-h-60 bg-cover bg-center rounded-lg py-10 md:py-[52px] md:px-[54px] text-white flex flex-col md:flex-row items-center"
                 style="background-image: url('{% static "core/images/course-create.png" %}')">
                <img class="h-full" src="{% static "core/images/gasyr-white-emblem.png" %}" alt="">
                <div class="md:ml-[106px] flex flex-col items-center md:items-start text-white">
                    <h2 class="text-[56px] w-full md:w-fit text-center md:text-start font-semibold leading-[68.49px] mb-5">Хотите загрузить<br/> свой курс?</h2>
                    <a class="px-16 py-[26px] border border-white rounded-lg inline-block" href="{% url "courses:create_course_step1" %}">Создать новый курс</a>
                </div>
            </div>
            <img class="absolute -inset-y-2 right-0 hidden md:block md:h-full" src="{% static "core/images/cats/course-create.png" %}" alt="">
        </div>

        <h1 class="text-[42px] font-bold mb-3">Мои курсы</h1>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-5 mb-10 ">
            {% for course in published_courses %}
                {% include 'core/components/course-card-edit.html' with course=course %}
            {% empty %}
                <div class="bg-white text-center col-span-2 py-[30px]">
                    <img class="inline-block" src="{% static 'core/images/cats/ball.png' %}" alt="">
                    <h2 class="font-bold text-[32px]">Тут еще ничего нет</h2>
                </div>
            {% endfor %}

        </div>

        <h1 class="text-[42px] font-bold mb-3">Черновики</h1>
        <div class="grid grid-cols-2 gap-5 mb-10">
            {% for course in unpublished_courses %}
                {% include 'core/components/course-card-edit.html' with course=course %}
            {% empty %}
                <div class="bg-white text-center col-span-2 py-[30px]">
                    <img class="inline-block" src="{% static 'core/images/cats/ball.png' %}" alt="">
                    <h2 class="font-bold text-[32px]">Тут еще ничего нет</h2>
                </div>
            {% endfor %}

        </div>
    </div>
    {% csrf_token %}
    {% comment %}
<h2>Welcome to the Home Page</h2>
<p>This is your home page. Navigate through the site from here.</p>

{% if request.user.role == "Teacher" or request.user.is_superuser %}
HI TEQACHER/ADMIN
    <a href="{% url 'users:grant_access' %}">Give Access</a>

{% endif %}
{% endcomment %}

{% endblock %}

core/templates/core/welcome.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Gasyr - foundation school{% endblock %}
{% block content %}
    {% include 'core/components/navbar-welcome.html' %}
    <div class="container px-5 md:px-0 content bg-no-repeat bg-top mx-auto font-[Qanelas] text-center"
         style="background-image: url('{% static 'core/images/background.png' %}'); background-size: 100%">
        <div class="border rounded-lg border-accent-red text-center inline-block py-10 md:py-16 px-5 md:px-12 mt-14 mb-64 bg-white">
            <h1 class="text-black-main font-semibold text-3xl md:text-[64px] md:leading-[76px]">
                Добро пожаловать <br/>в сообщество <span style="color: rgba(186, 32, 37, 1)">GasyrFoundation</span>
            </h1>
            <p class="text-base text-black-main mt-[14px] md:mt-0 mb-10" style="letter-spacing: 0.01rem">
                Платформа по подготовке в зарубежные ВУЗы от Gasyr Foundation School
            </p>
            <div class="flex flex-col gap-3 md:flex-row items-center justify-center">
                <a class="bg-accent-red w-full md:w-fit rounded-lg p-6 text-white" href="{% url 'users:login' %}">
                    Войти на платформу
                    <img class="inline ml-14" src="{% static 'core/icons/rounded-right-arrow-white.svg' %}" alt=""/>
                </a>
                <div class="border border-gray rounded-lg gap-[14px] md:gap-8 w-full md:w-fit p-4 md:p-2.5 md:pl-5 flex flex-col md:flex-row items-center">
                    <p class="text-base font-semibold text-[#4F4F4F]">Впервые у нас?</p>
                    <a class="border w-full md:w-fit border-accent-red rounded-lg py-5 px-12 text-accent-red block font-semibold" href="{% url 'users:signup' %}">
                        Регистрация
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% csrf_token %}
    {% include 'core/components/footer.html' %}
{% comment %}
<h2>Welcome to the Home Page</h2>
<p>This is your home page. Navigate through the site from here.</p>
{% if request.user.role == "Teacher" or request.user.is_superuser %}
HI TEQACHER/ADMIN
    <a href="{% url 'users:grant_access' %}">Give Access</a>
{% endif %}
{% endcomment %}
{% endblock %}