core/urls.py
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import HomePageView, WelcomePageView, MyCoursesPageView, CompletedCoursesPageView, CoursePageView, \
    get_week_dates

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('appointments/', include('appointments.urls')),
    path('chats/', include('chats.urls')),
    path('subjects/', include('subjects.urls')),
    path('schedule/', include('schedule.urls')),
    path('news/', include('news.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', WelcomePageView.as_view(), name='welcome'),
    path('home/', HomePageView.as_view(), name='home'),
    path('my-courses/', MyCoursesPageView.as_view(), name='my-courses'),
    path('completed-courses/', CompletedCoursesPageView.as_view(), name='completed-courses'),

    path('api/week-dates/', get_week_dates, name='week_dates'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView, ShowCodeView, LoginView, GrantAccessView, ProfileView, CheckAccessView, log_out, \
    change_password, create_teacher, StudentCheckProfileView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('show_code/', ShowCodeView.as_view(), name='show_code'),  # Ensure this is correct
    path('grant-access/', GrantAccessView.as_view(), name='grant_access'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('check-access/', CheckAccessView.as_view(), name='check-access'),
    path('change-password/', change_password, name='change_password'),

    path('student/<int:pk>/profile/', StudentCheckProfileView.as_view(), name='student_check_profile'),

    path('create-teacher/', create_teacher, name='create-teacher'),
]

users/models.py
import re
from datetime import timedelta, date

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.validators import EmailValidator

class CustomUserManager(BaseUserManager):
    def create_user(self, phone_number, password=None, **extra_fields):
        if not phone_number:
            raise ValueError('The Phone Number is mandatory')
        formatted_phone_number = re.sub(r'\D', '', phone_number)
        user = self.model(phone_number=formatted_phone_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(phone_number, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    ROLE_CHOICES = (
        ('Anonymous', 'Anonymous'),
        ('Student', 'Student'),
        ('Teacher', 'Teacher'),
        ('Mentor', 'Mentor'),
        ('Psychologist', 'Psychologist'),
        ('Orientologist', 'Orientologist'),
    )

    full_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=22, unique=True)
    user_city = models.CharField(max_length=100, choices=[(city, city) for city in
                                                          ['Astana', 'Almaty', 'Shymkent', 'Karaganda', 'Aktobe',
                                                           'Taraz', 'Pavlodar', 'Oskemen', 'Semey', 'Atyrau']])
    role = models.CharField(max_length=13, choices=ROLE_CHOICES, blank=True, null=True, default='Anonymous')
    login_code = models.CharField(max_length=7, blank=True, null=True, unique=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    has_access = models.BooleanField(default=False)
    email = models.EmailField(max_length=255, unique=True, validators=[EmailValidator()], null=True, blank=True)

    last_opened_content_id = models.PositiveIntegerField(null=True, blank=True)

    admission_country = models.CharField(max_length=255, verbose_name='Страна поступление', blank=True, null=True)
    education_class = models.CharField(max_length=100, verbose_name='Класс обучения', blank=True, null=True)
    registration_date = models.DateField(verbose_name='Дата регистрации', default=date.today, editable=True)
    contract_end_date = models.DateField(verbose_name='Дата окончание договора', blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['full_name', 'user_city']

    def save(self, *args, **kwargs):
        # If registration_date is set and contract_end_date is not set, calculate and set it
        if self.registration_date and not self.contract_end_date:
            self.contract_end_date = self.registration_date + timedelta(days=120)  # Approximately 4 months

        # Set has_access to True if the user is a Teacher
        if self.role == 'Teacher':
            self.has_access = True

        # Call the parent save method to ensure the instance is saved correctly
        super(CustomUser, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
import re

from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('full_name', 'phone_number', 'user_city')

CustomUser = get_user_model()

class CustomUserAuthenticationForm(AuthenticationForm):
    # Ensure the field name matches your custom user model's USERNAME_FIELD
    phone_number = forms.CharField(label="Phone Number", required=True)

    def __init__(self, *args, **kwargs):
        super(CustomUserAuthenticationForm, self).__init__(*args, **kwargs)
        # Remove the default 'username' field
        del self.fields['username']
        # Add or modify fields as necessary
        self.fields['phone_number'] = forms.CharField(label="Phone Number", required=True)

class AccessCodeForm(forms.Form):
    login_code = forms.CharField(max_length=10, label="Login Code", help_text="Enter the user's login code to grant access.", required=True)

class PasswordChangeForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput)
    re_old_password = forms.CharField(widget=forms.PasswordInput)
    new_password = forms.CharField(widget=forms.PasswordInput)
    re_new_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        re_new_password = cleaned_data.get('re_new_password')

        if new_password and re_new_password:
            if new_password != re_new_password:
                raise ValidationError("Пароли должны совпадать")


class ProfileUpdateForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False)
    class Meta:
        model = get_user_model()
        fields = ['full_name', 'phone_number', 'user_city', 'profile_picture', 'email']

    def __init__(self, *args, **kwargs):
        # Extract the user from kwargs and then call super
        self.user = kwargs.pop('user', None)
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and CustomUser.objects.exclude(pk=self.user.pk).filter(email=email).exists():
            raise forms.ValidationError("Почта уже используется")
        return email

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        formatted_phone_number = re.sub(r'\D', '', phone_number)  # Strip non-numeric characters

        if formatted_phone_number and self.user and self.user.phone_number != formatted_phone_number:
            if CustomUser.objects.filter(phone_number=formatted_phone_number).exists():
                raise forms.ValidationError("Этот номер телефона уже используется")
        return formatted_phone_number


class TeacherCreationForm(forms.ModelForm):
    first_name = forms.CharField(max_length=255, required=True)
    last_name = forms.CharField(max_length=255, required=True)
    phone_number = forms.CharField(max_length=22, required=True)  # Make sure to capture this in the form fields if you want to normalize it in the form

    class Meta:
        model = CustomUser
        fields = ['phone_number']

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        normalized_phone_number = re.sub(r'\D', '', phone_number)
        if not normalized_phone_number.startswith('7'):
            normalized_phone_number = '7' + normalized_phone_number
        return normalized_phone_number

    def save(self, commit=True):
        user = super().save(commit=False)
        user.full_name = f"{self.cleaned_data['first_name']} {self.cleaned_data['last_name']}"
        user.role = 'Teacher'
        user.user_city = "Almaty"  # Default city
        password = CustomUser.objects.make_random_password()
        user.set_password(password)
        if commit:
            user.save()
        return user, password

class StudentProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['admission_country', 'education_class', 'registration_date', 'contract_end_date']
        widgets = {
            'admission_country': forms.TextInput(attrs={'class': 'form-control'}),
            'education_class': forms.TextInput(attrs={'class': 'form-control'}),
            'registration_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'contract_end_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        }

users/templates/users/create_teacher.html
{% extends 'subjects/base.html' %}
{% load course_tags %}
{% load custom_filters %}

{% load static %}
{% load l10n %}

{% block flex-content %}
    {% include "subjects/components/crm2-mentor-sidebar.html" %}
    <main class="main flex-1 pb-[100px] w-3/4 font-[Qanelas]">
        {% include "subjects/components/crm2-header.html" %}
        <div class="pt-[50px] ml-[40px] mr-[78px] grid ">
            <h1 class="text-[42px] text-black-main font-semibold leading-[52px] mb-[24px]">Учителя</h1>
            <div class="grid gap-[16px]">
                <div class="bg-white flex justify-between rounded-md shadow-[0px_4px_20px_0px_#00000014] h-[630px]">
                    <div class="flex flex-col justify-center pl-[42px] pr-[28px] w-2/5">
                        <h3 class="text-black-main text-[32px] leading-[45px] font-semibold mb-[12px]">
                            Добавить учителя в систему
                        </h3>
                        <form method="post" action="{% url 'users:create-teacher' %}"
                              class="w-full space-y-[8px]">
                            {% csrf_token %}
                            <div>
                                <input type="text" name="first_name" required
                                       class="w-full h-[75px] border-[1px] border-[#CDCDCD] rounded-md px-[16px] focus:outline-none font-regular text-[16px] leading-[22px] text-black-main"
                                       placeholder="Введите имя учителя">
                                {% for error in form.first_name.errors %}
                                    <p class="text-red-500 text-xs italic">{{ error }}</p>
                                {% endfor %}
                            </div>
                            <div>
                                <input type="text" name="last_name" id="id_last_name" required
                                       class="w-full h-[75px] border-[1px] border-[#CDCDCD] rounded-md px-[16px] focus:outline-none font-regular text-[16px] leading-[22px] text-black-main"
                                       placeholder="Введите фамилию учителя">
                                {% for error in form.last_name.errors %}
                                    <p class="text-red-500 text-xs italic">{{ error }}</p>
                                {% endfor %}
                            </div>
                            <div class="relative">
                                <input type="tel" name="phone_number"
                                       id="id_phone_number" value="+7 (___) ___ __ __" required
                                       class="w-full h-[75px] border-[1px] border-[#CDCDCD] rounded-md px-[16px] pl-14 focus:outline-none font-regular text-[16px] leading-[22px] text-black-main"
                                       placeholder="Enter phone number">
                                <div class="absolute top-7 left-2 pl-3
                                    flex items-center
                                    pointer-events-none">
                                    <img src="{% static "core/icons/kz.png" %}" alt="">
                                </div>
                                {% for error in form.phone_number.errors %}
                                    <p class="text-red-500 text-xs italic">{{ error }}</p>
                                {% endfor %}
                            </div>
                            <div>
                                <button type="submit"
                                        class="w-full bg-accent-red text-white rounded-md h-[75px] flex items-center justify-center text-[16px] leading-[22px] font-semibold">
                                    Создать аккаунт
                                </button>
                            </div>
                        </form>
                    </div>
                    {% if phone %}
                        <div class="w-3/5 rounded-r-md flex justify-center items-center bg-center bg-no-repeat bg-cover"
                             style="background-image: url({% static 'core/images/crm2/teacherBG.png' %});">
                            <div class="bg-white w-[450px] rounded-md pt-[40px] pl-[32px] pr-[77px] pb-[46px] grid gap-[12px]">
                                <div class="grid gap-[2px]">
                                    <label for="number"
                                           class="text-black-main text-[24px] leading-[33px] font-semibold">Вход по
                                        номеру
                                        телефона</label>
                                    <div class="flex items-center relative">
                                        <img src="{% static 'core/icons/kz.png' %}" alt="Kazakhstan Flag"
                                             class="max-w-[20px] max-h-[25px] absolute left-[20px]">
                                        <input type="text" id="id_phone_number" value="{{ phone|format_phone_number }}"
                                               class="h-[56px] pl-[52px] pr-[14px] border-[1px] border-[#CDCDCD] rounded-md w-full focus:outline-none text-[18px] leading-[26px] font-semibold text-black-main"
                                               readonly>
                                    </div>
                                </div>
                                <div class="grid gap-[2px]">
                                    <label for="password"
                                           class="text-black-main text-[24px] leading-[33px] font-semibold mb-[2px]">Пароль</label>
                                    <div class="flex items-center relative">
                                        <input type="text" id="password" value="{{ phone|get_pass:request }}"
                                               class="h-[56px] px-[14px] border-[1px] border-[#CDCDCD] rounded-md w-full focus:outline-none text-[18px] leading-[26px] font-medium text-black-main"
                                               readonly>
                                        <button onclick="copyPassword()"
                                                class="absolute -right-[35px] max-w-[20px] max-h-[22px] focus:outline-none">
                                            <img src="{% static 'assets/copyIcon.svg' %}" alt="">
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="w-3/5 rounded-r-md flex justify-center items-end bg-center bg-no-repeat bg-cover"
                             style="background-image: url({% static 'core/images/crm2/teacherBG.png' %});">
                            <img src="{% static 'core/images/cats/suit.png' %}" id="cat_img"
                                 class="max-h-[555px] max-w-[534px]">
                        </div>
                    {% endif %}
                </div>
                <div class="bg-white shadow-[0px_4px_20px_0px_#00000014] rounded-md p-[14px]">
                    <div class="numberOfStudents pt-[33px] px-[30px] pb-[37px] bg-[#FAFAFA] rounded-sm mt-[10px]">
                        <ul class="grid gap-[16px] max-h-[425px] overflow-y-auto px-[15px]">
                            {% for teacher in teachers %}
                                <li class="flex justify-between w-full items-center">
                                    <div class="gap-[16px] flex items-center w-[230px]">
                                        <img src="{{ teacher.photo.url }}" alt=""
                                             class="max-h-[32px] max-w-[32px] rounded-full">
                                        <h5 class="font-semibold text-[16px] leading-[20px] text-black-main">{{ teacher.full_name }}</h5>
                                    </div>
                                    <div class="flex gap-[8px] items-center w-[200px]">
                                        <img src="{% static 'core/icons/phone-fill-accent-red.svg' %}" alt=""
                                             class="max-w-[16px] max-h-[16px]">
                                        <span class="font-semibold text-[16px] leading-[22px] text-black-main">{{ teacher.phone_number|format_phone_number }}</span>
                                    </div>
                                    <div class="city flex gap-[8px] items-center w-[160px]">
                                        <img src="{% static 'core/icons/city-fill-accent-red.svg' %}" alt=""
                                             class="max-w-[16px] max-h-[16px]">
                                        <span class="font-semibold text-[16px] leading-[22px] text-black-main">{{ teacher.user_city }}</span>
                                    </div>
                                    <a href="{% url 'users:create-teacher' %}?phone={{ teacher.phone_number }}" class="underline font-semibold text-[16px] w-[200px] leading-[22px] text-black-main hover:no-underline">
                                        Редактировать данные
                                    </a>

                                </li>
                            {% empty %}
                                <li>No teachers found.</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script>
        function copyPassword() {
            var copyText = document.getElementById("password");
            copyText.select();
            document.execCommand("copy");
            alert("Password copied to clipboard!");
        }

        document.getElementById('id_phone_number').addEventListener('input', function (e) {
            formatPhoneNumber(e);
        });

        function formatPhoneNumber(e) {
            var input = e.target.value.replace(/[^\d]/g, ''); // Remove all non-numeric characters

            // Ensure the input starts with '7' (the country code for Kazakhstan)
            if (!input.startsWith('7')) {
                input = '7' + input;
            }

            // Limit the length to 11 digits (including the country code '7')
            input = input.substring(0, 11);

            var formattedInput = '+7 ('; // Start with the country code and opening parenthesis

            // Remove the country code ('7') and then format the rest
            input = input.substring(1); // Remove the '7' to start formatting

            // Dynamically add formatting based on the current length of the input
            for (var i = 0; i < input.length; i++) {
                if (i === 3) {
                    formattedInput += ') '; // Close the parenthesis after the area code
                } else if (i === 6 || i === 8) {
                    formattedInput += ' - '; // Add dashes after the 6th and 8th digits
                }
                formattedInput += input[i];
            }

            // Update the input field with the dynamically formatted value
            e.target.value = formattedInput;
        }
    </script>
{% endblock %}

users/templates/users/grant_access.html
{% extends 'core/base.html' %}

{% block content %}
<h2>Grant Access</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="grant_access">Grant Access</button>
</form>

{% if user_info %}
    <h3>User Information:</h3>
    <p><strong>Full Name:</strong> {{ user_info.full_name }}</p>
    <p><strong>Phone Number:</strong> {{ user_info.phone_number }}</p>
    <p><strong>City:</strong> {{ user_info.user_city }}</p>
    <p><strong>Has Access:</strong> {{ user_info.has_access|yesno:"Yes,No" }}</p>
{% endif %}

{% endblock %}

users/templates/users/signup.html
{% extends "core/base.html" %}
{% load static %}
{% block body-classes %}bg-accent-red{% endblock %}
{% block content %}

    {% include 'core/components/navbar-light-transparent.html' %}


    <div class="container md:content min-h-screen mx-auto relative flex md:justify-end flex-col md:flex-row px-5 md:px-0 ">
    {% comment %} <div class="container    content          mx-auto relative flex    justify-end flex-col md:flex-row px-5 md:px-0 "> {% endcomment %}

        <div class="md:mb-20 flex md:ml-auto md:w-full  md:flex-row justify-center md:justify-end items-center md:items-start">
            <div class="bg-light-gray w-full md:min-w-[410px] md:w-fit rounded-lg text-center px-4 pb-7 pt-7 md:pb-7 md:pt-14 md:max-w-none">
                <h2 class="font-bold text-2xl md:text-2xl mb-5 text-black-main">Давайте знакомиться!</h2>
                <form class="mb-7 w-full" method="post" action="{% url 'users:signup' %}" id="signup-form">
                    {% csrf_token %}
                    <div class="relative mb-4">
                        <input class="pl-4 py-5 md:py-4 w-full border border-[#CDCDCD] rounded-lg focus:outline-none placeholder:text-black-main text-sm md:text-base"
                               type="text" name="full_name" id="id_full_name" placeholder="Имя и Фамилия" required>
                        <div class="absolute top-1/2 left-3 transform -translate-y-1/2 flex items-center pointer-events-none">
                        </div>
                    </div>
                    <div class="relative mb-4">
                        <input class="pl-11 py-5 md:py-4 w-full border border-[#CDCDCD] rounded-lg focus:outline-none placeholder:text-black-main text-sm md:text-base"
                               type="text" name="phone_number" id="id_phone_number" value="+7 (___) ___ __ __" required>
                        <div class="absolute top-1/2 left-3 transform -translate-y-1/2 flex items-center pointer-events-none">
                            <img class="h-6 w-6" src="{% static "core/icons/kz.png" %}" alt="">
                        </div>
                    </div>
                    <div class="relative mb-4">
                        <select class="pl-11 py-5 md:py-4 w-full border border-[#CDCDCD] rounded-lg placeholder:text-black-main text-sm md:text-base appearance-none"
                                name="user_city" id="id_user_city" required>
                            <option selected value="_">Ваш город</option>
                            <option value="Astana">Астана</option>
                            <option value="Almaty">Алматы</option>
                            <option value="Shymkent">Шымкент</option>
                            <option value="Karaganda">Караганда</option>
                            <option value="Aktobe">Актобе</option>
                            <option value="Taraz">Тараз</option>
                            <option value="Pavlodar">Павлодар</option>
                            <option value="Oskemen">Оскемен</option>
                            <option value="Semey">Семей</option>
                            <option value="Atyrau">Атырау</option>
                        </select>
                        <div class="absolute top-1/2 left-3 transform -translate-y-1/2 flex items-center pointer-events-none">
                            <img class="h-6 w-6" src="{% static "core/icons/arrow-down-s-fill.svg" %}" alt="">
                        </div>
                    </div>
                    <input class="pl-4 py-5 md:py-4 w-full border border-[#CDCDCD] focus:outline-none rounded-lg mb-3 placeholder:text-black-main text-sm md:text-base"
                           type="password" name="password" id="id_password" placeholder="Пароль" required><br>
                    <input class="pl-4 py-5 md:py-4 w-full border border-[#CDCDCD] focus:outline-none rounded-lg  mb-3 placeholder:text-black-main text-sm md:text-base"
                           type="password" name="re_password" id="id_re_password" placeholder="Повторите пароль" required><br>
                    <button class="bg-accent-red rounded-lg py-5 md:py-4 font-semibold text-white text-sm md:text-base w-full"
                            type="submit">Стать частью Gasyr
                    </button>
                </form>


                <div>
                    <h4 class="text-black-main font-semibold text-base md:text-lg mb-2.5">Зарегистрироваться через соц. сети</h4>
                    <div class="flex justify-center space-x-4">
                        <a class="p-4 md:p-6 border border-gray bg-white rounded-full inline-block" href="#">
                            <img class="h-5 w-5 md:h-7 md:w-7" src="{% static "core/icons/google-icon-svgrepo-com.svg" %}" alt="">
                        </a>
                        <a class="p-4 md:p-6 border border-gray bg-white rounded-full inline-block" href="#">
                            <img class="h-5 w-5 md:h-7 md:w-7" src="{% static "core/icons/vk-svgrepo-com.svg" %}" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="hidden md:block relative bg-no-repeat bg-top bg-cover mt-4 mb-10">
            <div class="absolute" style="background-image: url('{% static "core/images/background-stars.png" %}')"></div>
        </div>

        
        <div class="relative md:absolute md:left-24 md:-top-[50px] md:-bottom-10 md:-z-10">
            <img class="h-full hidden md:block" src="{% static "core/images/signup-guy.png" %}" alt="">
            <div class="absolute hidden md:block bottom-0 left-auto right-auto z-20  bg-white rounded-lg py-6 px-8 text-center mxmx-auto mb-16 md:bottom-36 md:left-36">
                <h2 class="text-lg md:text-2xl text-black-main font-bold">Халыкбердиев Якуб</h2>
                <p class="text-xs md:text-sm text-black-main font-medium">Основатель школы</p>
            </div>
            <div class="absolute hidden -bottom-6 left-5 right-5 z-50 bg-white rounded-lg py-6 px-5 text-center">
                <h2 class="text-[26px] md:text-2xl text-black-main font-bold">Халыкбердиев Якуб</h2>
                <p class="text-xs md:text-sm text-black-main font-medium">Основатель школы</p>
            </div>
        </div>


    </div>

    {% include "core/components/footer.html" %}

    <!-- Include jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Include Inputmask -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/5.0.5/jquery.inputmask.min.js"></script>

    <script>
        document.getElementById('id_phone_number').addEventListener('input', function (e) {
            formatPhoneNumber(e);
        });

        function formatPhoneNumber(e) {
            var input = e.target.value.replace(/[^\d]/g, ''); // Remove all non-numeric characters

            // Ensure the input starts with '7' (the country code for Kazakhstan)
            if (!input.startsWith('7')) {
                input = '7' + input;
            }

            // Limit the length to 11 digits (including the country code '7')
            input = input.substring(0, 11);

            var formattedInput = '+7 ('; // Start with the country code and opening parenthesis

            // Remove the country code ('7') and then format the rest
            input = input.substring(1); // Remove the '7' to start formatting

            // Dynamically add formatting based on the current length of the input
            for (var i = 0; i < input.length; i++) {
                if (i === 3) {
                    formattedInput += ') '; // Close the parenthesis after the area code
                } else if (i === 6 || i === 8) {
                    formattedInput += ' - '; // Add dashes after the 6th and 8th digits
                }
                formattedInput += input[i];
            }

            // Update the input field with the dynamically formatted value
            e.target.value = formattedInput;
        }
    </script>

{% endblock %}