core/urls.py
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import HomePageView, WelcomePageView, MyCoursesPageView, CompletedCoursesPageView, CoursePageView, \
    get_week_dates

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('appointments/', include('appointments.urls')),
    path('chats/', include('chats.urls')),
    path('subjects/', include('subjects.urls')),
    path('schedule/', include('schedule.urls')),
    path('news/', include('news.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', WelcomePageView.as_view(), name='welcome'),
    path('home/', HomePageView.as_view(), name='home'),
    path('my-courses/', MyCoursesPageView.as_view(), name='my-courses'),
    path('completed-courses/', CompletedCoursesPageView.as_view(), name='completed-courses'),

    path('api/week-dates/', get_week_dates, name='week_dates'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/urls.py
from django.urls import path, re_path
from .views import (
    CourseListView, CourseDetailView, LessonCreateView,
    ModuleDetailView, LessonDetailView,
    CreateCourseStep1View, CreateCourseStep2View, CreateOrEditTestView, ModuleCreateView, AddStudentsView,
    add_student_to_course, TakeTestView, test_result_view, search_students, EditCourseView, CourseDelete,
    delete_literature, CourseFinalTestView, SuccessVideoLinkEditView, bulk_create_lessons, CourseModulesView,
    ModuleCreateViewAPI, LessonCreateViewAPI, LiteratureCreateViewAPI, LiteratureDeleteViewAPI, CreateCourseStep3View,
    CreateCourseStep4View, CreateCourseStep5View, CreateCourseEndingView, student_results_view, publishCourse,
    student_test_results_view, HomeworkCreateViewAPI, HomeworkDetailView, LiteratureDetailView, HomeworkDeleteViewAPI,
    UploadLiteratureView, StudentHomeworkUploadView
)
from core.views import CoursePageView, CourseStudentLecturePageView, course_redirect, CourseStudentTestPageView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='course_list'),
    path('<int:pk>/', CoursePageView.as_view(), name='course_detail'),
    path('student/<int:pk>/', course_redirect, name='course_start'),
    path('student/<int:pk>/<int:module_id>/<int:lesson_id>/lecture', CourseStudentLecturePageView.as_view(), name='course_student_lecture'),
    path('student/<int:pk>/<int:module_id>/<int:lesson_id>/test', CourseStudentTestPageView.as_view(), name='course_student_test_lesson'),
    path('student/<int:pk>/<int:module_id>/test', CourseStudentTestPageView.as_view(), name='course_student_test_module'),
    path('student/<int:pk>/test', CourseStudentTestPageView.as_view(), name='course_student_test_course'),
    path('edit/<int:pk>/', CourseDetailView.as_view(), name='course_detail_edit'),
    path('publish/<int:pk>/', publishCourse, name='course_publish'),
    path('edit/<int:pk>/about/', EditCourseView.as_view(), name='course_detail_edit_about'),
    path('delete/<int:pk>/', CourseDelete.as_view(), name='course_delete'),
    path('create/step1/', CreateCourseStep1View.as_view(), name='create_course_step1'),
    path('create/step2/', CreateCourseStep2View.as_view(), name='create_course_step2'),
    path('create/step3/<int:course_id>', CreateCourseStep3View.as_view(), name='create_course_step3'),
    path('create/step4/<int:course_id>', CreateCourseStep4View.as_view(), name='create_course_step4'),
    path('create/step5/<int:course_id>', CreateCourseStep5View.as_view(), name='create_course_step5'),
    path('create/ending/<int:course_id>', CreateCourseEndingView.as_view(), name='create_course_ending'),
    path('<int:course_id>/module/create/', ModuleCreateViewAPI.as_view(), name='module_create'),
    path('<int:module_id>/lesson/create/', LessonCreateViewAPI.as_view(), name='lesson_create'),

    path('literature/create/<int:lesson_id>/', LiteratureCreateViewAPI.as_view(), name='literature-create'),
    path('literature/delete/<int:literature_id>/', LiteratureDeleteViewAPI.as_view(), name='literature-delete'),

    path('<int:lesson_id>/homework/create/', HomeworkCreateViewAPI.as_view(), name='homework_create'),

    path('<int:course_id>/<int:module_id>/<int:pk>/homework/', HomeworkDetailView.as_view(),
                       name='course_student_homework'),

    path('student/<int:course_id>/<int:module_id>/<int:lesson_id>/literature/',
                       LiteratureDetailView.as_view(), name='course_student_literature'),

    path('homework/<int:homework_id>/delete/', HomeworkDeleteViewAPI.as_view(), name='homework-delete'),

    path('module/<int:pk>/', ModuleDetailView.as_view(), name='module_detail'),
    path('<int:pk>/final_test/edit', CourseFinalTestView.as_view(), name='final_test_creation'),
    path('<int:pk>/success_video/edit', SuccessVideoLinkEditView.as_view(), name='success_video_edit'),
    path('lesson/<int:pk>/', LessonDetailView.as_view(), name='lesson_detail'),
    path('<str:parent_type>/<int:parent_id>/test/', CreateOrEditTestView.as_view(), name='create_edit_test'),
    path('course/<int:pk>/add-students/', AddStudentsView.as_view(), name='add_students'),
    path('<int:course_id>/add-student/<int:student_id>/', add_student_to_course, name='add_student_to_course'),
    path('course/search-students/', search_students, name='search_students'),

    path('<int:course_id>/student/<str:student_login_code>', student_results_view, name='student_results'),
    path('<int:course_id>/student/<str:student_login_code>/<int:submission_id>', student_test_results_view, name='student_test_results'),

    path('test/take/<int:course_id>/<int:module_id>/<int:lesson_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_lesson'),
    path('test/take/<int:course_id>/<int:module_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_module'),
    path('test/take/<int:course_id>/<int:test_id>/', TakeTestView.as_view(), name='take_test_course'),
    re_path(r'^test/result/(?P<score>\d+\.\d+)/$', test_result_view, name='test_result'),

    path('course/<int:course_id>/module/', ModuleDetailView.as_view(), name='module_detail'),
    path('module/<int:module_id>/bulk-create-lessons/', bulk_create_lessons, name='bulk_create_lessons'),
    path('module/<int:module_id>/update-module-and-lessons/', bulk_create_lessons, name='update_module_and_lessons'),
    path('<int:course_id>/modules/api/', CourseModulesView.as_view(), name='course-modules'),

    path('lessons/<int:lesson_id>/literature/upload/', UploadLiteratureView.as_view(),
                       name='upload-literature'),

    path('<int:course_id>/<int:module_id>/<int:lesson_id>/homework/upload/', StudentHomeworkUploadView.as_view(), name='student_homework_upload'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/views.py
import json
import os
import traceback

import magic
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.contenttypes.models import ContentType
from django.core.files.storage import FileSystemStorage
from django.db import IntegrityError, transaction
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse, HttpResponseRedirect, \
    HttpResponseNotAllowed, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView, DetailView, View, TemplateView
from django.views.generic.edit import CreateView, FormView, UpdateView
from rest_framework import status
from rest_framework.parsers import MultiPartParser, FormParser, JSONParser
from rest_framework.response import Response
from rest_framework.views import APIView

from users.models import CustomUser
from .forms import CourseFormStep1, CourseFormStep2, LessonForm, TestForm, ModuleForm, AddStudentForm, CourseForm, \
    AnswerForm, QuestionForm, SuccessVideoLinkForm, HomeworkForm
from .models import Course, Module, Lesson, Test, Question, Answer, TestSubmission, LessonLiterature, Homework, \
    StudentHomework
from .serializers import CourseSerializer, ModuleSerializer, LessonSerializer, LiteratureSerializer, HomeworkSerializer


class CourseDelete(DetailView):
    model = Course

    def post(self, request, *args, **kwargs):
        pass


class EditCourseView(View):

    def get(self, request, *args, **kwargs):
        course = Course.objects.get(pk=self.kwargs["pk"])
        form = CourseForm(instance=course)
        return render(request, 'courses/course/edit_course.html', {'form': form, 'course': course})

    def post(self, request, *args, **kwargs):
        form = CourseForm(request.POST, request.FILES)
        course = Course.objects.get(id=self.kwargs["pk"])
        print(form.is_valid())
        if form.is_valid():
            course.course_name = form.cleaned_data["course_name"]
            course.mini_description = form.cleaned_data["mini_description"]
            course.big_description = form.cleaned_data["big_description"]
            course.course_time = form.cleaned_data["course_time"]
            course.course_difficulty = form.cleaned_data["course_difficulty"]
            course.full_description = form.cleaned_data["full_description"]

            if 'course_picture' in request.FILES:
                course.course_picture = form.cleaned_data["course_picture"]

            course.save()
            return redirect('courses:course_detail_edit', pk=course.id)

        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            module_form = ModuleForm(request.POST, request.FILES)
            if module_form.is_valid():
                new_module = module_form.save(commit=False)
                new_module.course_id = self.kwargs["pk"]
                new_module.save()
                return JsonResponse({'module_id': new_module.id, 'module_name': new_module.name}, status=200)
            else:
                return JsonResponse({'error': module_form.errors}, status=400)

        return render(request, 'courses/course/edit_course.html', {'form': form, 'course': course})


class CreateCourseStep1View(View):
    def get(self, request, *args, **kwargs):
        form = CourseFormStep1()
        return render(request, 'courses/course/create_course_step1.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = CourseFormStep1(request.POST, request.FILES)
        if form.is_valid():
            course_step1_data = form.cleaned_data

            # Handle file saving
            course_picture = form.cleaned_data.get('course_picture')
            if course_picture and hasattr(course_picture, 'name'):
                fs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'temp'))
                filename = fs.save(course_picture.name, course_picture)
                file_path = fs.path(filename)
                request.session['course_picture_path'] = file_path
            else:
                # If no file is uploaded, set course_picture_path to None
                request.session['course_picture_path'] = None

            course_step1_data.pop('course_picture', None)
            request.session['course_step1_data'] = course_step1_data
            return redirect('courses:create_course_step2')

        return render(request, 'courses/course/create_course_step1.html', {'form': form})
from django.core.files import File

class CreateCourseStep2View(View):
    def get(self, request, *args, **kwargs):
        form = CourseFormStep2()
        return render(request, 'courses/course/create_course_step2.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = CourseFormStep2(request.POST)
        if form.is_valid():
            course_data = request.session.get('course_step1_data', {})
            course = Course(**course_data, **form.cleaned_data)
            course.created_by = request.user

            # Handle file retrieval and attachment only if a custom picture was uploaded
            course_picture_path = request.session.get('course_picture_path')
            if course_picture_path:
                with open(course_picture_path, 'rb') as f:
                    course.course_picture.save(os.path.basename(course_picture_path), File(f), save=False)

            course.save()

            # Clean up session data and temporary file if exists
            del request.session['course_step1_data']
            if 'course_picture_path' in request.session and course_picture_path:
                os.remove(course_picture_path)
                del request.session['course_picture_path']

            return redirect('courses:create_course_step3', course_id=course.id)

        return render(request, 'courses/course/create_course_step2.html', {'form': form})


class CreateCourseStep3View(View):
    def get(self, request, *args, **kwargs):
        course = Course.objects.get(id=self.kwargs["course_id"])
        return render(request, 'courses/course/create_course_step3.html', {'course': course})


class CreateCourseStep4View(View):
    def get(self, request, *args, **kwargs):
        course = Course.objects.get(id=self.kwargs["course_id"])
        return render(request, 'courses/course/create_course_step4.html', {'course': course})


class CreateCourseStep5View(View):
    def get(self, request, *args, **kwargs):
        course = Course.objects.get(id=self.kwargs["course_id"])
        return render(request, 'courses/course/create_course_step5.html', {'course': course})


class CreateCourseEndingView(View):
    def get(self, request, *args, **kwargs):
        course = Course.objects.get(id=self.kwargs["course_id"])
        return render(request, 'courses/course/create_course_ending.html', {'course': course})


from django.db.models import Prefetch, Q


class CourseListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Course
    template_name = 'courses/course/course_list.html'
    context_object_name = 'courses'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.role in ['Student', 'Teacher', 'Mentor']

    def get_queryset(self):
        user = self.request.user
        queryset = Course.objects.all()

        # Prefetch related modules and lessons to avoid N+1 queries
        queryset = queryset.prefetch_related(
            Prefetch('modules', queryset=Module.objects.prefetch_related('lessons'))
        )

        return queryset

    def post(self, request, *args, **kwargs):
        data_type = request.POST.get('data_type', 'all')
        user = self.request.user

        if data_type == 'mine':
            courses = user.courses.prefetch_related('modules__lessons')
        elif data_type == 'ended':
            courses = user.courses.prefetch_related('modules__lessons')
            courses = [course for course in courses if course.calculate_completion_percentage(user) >= 100]
        else:
            courses = self.get_queryset()

        for course in courses:
            course.completion_percentage = course.calculate_completion_percentage(user)

        context = {
            'course_data': [{'course': course, 'enrolled': True, 'completion': course.completion_percentage} for course
                            in courses]}
        html = render_to_string('courses/_course_list_partial.html', context, request=request)
        return JsonResponse({'html': html})


class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'courses/course/course_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object()
        user = self.request.user

        # Getting content type for Course
        course_type = ContentType.objects.get_for_model(course)
        test = Test.objects.filter(content_type=course_type, object_id=course.id).first()

        is_creator_or_superuser = user.is_superuser or course.created_by == user
        is_teacher = user.role == 'Teacher'
        is_enrolled = course.is_user_enrolled(user)

        context.update({
            'course': course,
            'test': test,
            'test_exists': test is not None,
            'creator_full_name': course.created_by.full_name,
            'creator_profile_picture': course.created_by.profile_picture.url if course.created_by.profile_picture else None,
            'can_modify_course': is_creator_or_superuser or is_teacher,
            'students': course.users.filter(role='Student').all() if is_creator_or_superuser or is_teacher else [],
            'is_enrolled': is_enrolled,

courses/templates/courses/_course_list_partial.html
<!-- _course_list_partial.html -->
{% for data in course_data %}
    <div>
        <a href="{% url 'courses:course_detail' pk=data.course.pk %}">{{ data.course.course_name }}</a>
        {% if data.enrolled %}
            {% if data.completion == 0 %}
                <p>Начать прохождение</p>
            {% elif data.completion == 100 %}
                <p>Вы прошли курс</p>
            {% else %}
                <p>Completion: {{ data.completion|floatformat:2 }}%</p>
            {% endif %}
        {% else %}
            <p>Доступен к покупке</p>
        {% endif %}
    </div>
{% empty %}
    <p>No courses available.</p>
{% endfor %}

courses/templates/courses/lesson_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h2>Lesson: {{ lesson.lesson_name }}</h2>

    <!-- Conditionally display Take Test or Create/Edit Test buttons -->
    {% if test %}
        {% if is_enrolled or is_creator_or_superuser %}
            <a href="{% url 'courses:take_test' test_id=test.pk %}">Take Test</a>
        {% endif %}
        {% if is_creator_or_superuser %}
            <a href="{% url 'courses:create_edit_test' parent_type='lesson' parent_id=lesson.pk %}">Edit Test</a>
        {% endif %}
    {% else %}
        {% if is_creator_or_superuser %}
            <a href="{% url 'courses:create_edit_test' parent_type='lesson' parent_id=lesson.pk %}">+ Create Test</a>
        {% endif %}
    {% endif %}
{% endblock %}

courses/templates/courses/lesson_form.html
{% extends 'core/base.html' %}

{% block content %}
<h2>Add New Lesson</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Lesson</button>
</form>
{% endblock %}

courses/templates/courses/student_results.html
{% extends 'core/base.html' %}
{% load course_tags %}
{% load static %}

{% block title %}{{ course.course_name }}{% endblock %}
{% block body-classes %}bg-whiteless{% endblock %}
{% block content %}
    {% include "core/components/navbar-main-without-links.html" %}

    <div class="container content bg-no-repeat bg-top mx-auto font-[Qanelas] text-black-main pt-14">
        <section class="pt-[42px]">
            <div class="px-10 pt-9 pb-10 rounded-[10px] flex items-center gap-[36px] container-test mb-5 bg-cover bg-center"
                 style="background-image: url('{% static 'core/images/gasyr-accent-red-background.png' %}')">
                <div class="w-[210px] h-[210px] rounded-[100px] overflow-hidden">
                    <img src="{% if student.profile_picture %}
                                /{{ student.profile_picture }}
                            {% else %}
                                {% static "core/images/default-user.svg" %}
                            {% endif %}"
                         alt="avatar" class="w-full h-full object-cover rounded-full"/>
                </div>
                <div>
                    <h1 class="mb-[16px] text-[56px] font-[600] text-white">{{ student.full_name }}</h1>
                    <p class="mb-[20px] text-[24px] text-white">Ученик</p>
                    <div class="flex gap-[12px] text-white">
                        <p><img src="{% static 'core/icons/kz.png' %}" alt=""></p>
                        <p class="mr-[20px]">{{ student.phone_number|format_phone_number }}</p>
                        <p>г. {{ student.city }}</p>
                    </div>
                </div>
            </div>

            <div class="px-10 pt-9 pb-10 rounded-[10px] bg-white container-test mb-5">
                {% for module in modules %}
                    <table class="mb-8 w-full">
                        <thead class="border-b border-[#CDCDCD]">
                        <tr class="text-[16px] text-black-main font-[700]">
                            <th class="pb-4 text-[24px] w-[30%] text-left">Модуль {{ forloop.counter }}: {{ module.module_name }}</th>
                            <th class="pb-4 text-center w-[15%]">Дата прохождения</th>
                            <th class="pb-4 text-center w-[15%]">Домашка</th>
                            <th class="pb-4 text-right">Результат</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for lesson in module.lessons.all %}
                            <tr class="border-b border-[#CDCDCD] text-[16px] text-black-main font-[700]">
                                <th class="py-4 text-left">Тестирование за урок: {{ lesson.lesson_name }}</th>
                                {% with submission=sub_test_lesson|get_lesson_submission:lesson %}
                                    {% if submission %}
                                        <th class="">{{ submission.completed|date:"d.m.Y" }}</th>
                                        <th class="text-center">
                                            {% with homework=homework_submissions|get_homework_submission:lesson %}
                                                {% if homework %}
                                                    <a href="{{ homework.file.url }}" class="text-blue-ielts underline hover:text-blue-700">Скачать</a>
                                                {% else %}
                                                    <p>Не выполнено</p>
                                                {% endif %}
                                            {% endwith %}
                                        </th>
                                        <th class="text-right">
                                            <a class="text-blue-ielts underline hover:text-blue-700"
                                               href="{% url 'courses:student_test_results' course_id=course.id student_login_code=student.login_code submission_id=submission.id %}">
                                                Результат
                                            </a>
                                        </th>
                                    {% else %}
                                        <th class=""></th>
                                        <th class="text-center"><p>Не выполнено</p></th>
                                        <th class="text-right"><p>Не пройден</p></th>
                                    {% endif %}
                                {% endwith %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endfor %}

                <!-- Модульные тесты -->
                <h2 class="text-[24px] text-black-main font-[700]">Модульные тесты</h2>
                <table class="mb-8 w-full">
                    <thead class="border-b border-[#CDCDCD]">
                    <tr class="text-[16px] text-black-main font-[700]">
                        <th class="pb-4 text-left w-[50%]">Название модуля</th>
                        <th class="pb-4 text-center w-[25%]">Дата прохождения</th>
                        <th class="pb-4 text-right w-[25%]">Результат</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for module in modules %}
                        {% with submission=sub_test_module|get_module_submission:module %}
                            <tr class="border-b border-[#CDCDCD] text-[16px] text-black-main font-[700]">
                                <th class="py-4 text-left">{{ module.module_name }}</th>
                                {% if submission %}
                                    <th class="text-center">{{ submission.completed|date:"d.m.Y" }}</th>
                                    <th class="text-right">
                                        <a class="text-blue-ielts underline hover:text-blue-700"
                                           href="{% url 'courses:student_test_results' course_id=course.id student_login_code=student.login_code submission_id=submission.id %}">
                                            Результат
                                        </a>
                                    </th>
                                {% else %}
                                    <th class="text-center">---</th>
                                    <th class="text-right">---</th>
                                {% endif %}
                            </tr>
                        {% endwith %}
                    {% endfor %}
                    </tbody>
                </table>

                <!-- Финальный тест курса, если он существует -->
                {% if sub_test_course %}
                    <h2 class="text-[24px] text-black-main font-[700]">Финальный тест курса</h2>
                    <table class="mb-8 w-full">
                        <thead class="border-b border-[#CDCDCD]">
                        <tr class="text-[16px] text-black-main font-[700]">
                            <th class="pb-4 text-left w-[50%]">Тест</th>
                            <th class="pb-4 text-center w-[25%]">Дата прохождения</th>
                            <th class="pb-4 text-right w-[25%]">Результат</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for submission in sub_test_course %}
                            <tr class="border-b border-[#CDCDCD] text-[16px] text-black-main font-[700]">
                                <th class="py-4 text-left">Финальный тест курса</th>
                                <th class="text-center">{{ submission.completed|date:"d.m.Y" }}</th>
                                <th class="text-right">
                                    <a class="text-blue-ielts underline hover:text-blue-700"
                                       href="{% url 'courses:student_test_results' course_id=course.id student_login_code=student.login_code submission_id=submission.id %}">
                                        Результат
                                    </a>
                                </th>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h2 class="text-[24px] text-black-main font-[700]">Финальный тест курса</h2>
                    <p>Финальный тест не пройден.</p>
                {% endif %}

            </div>
        </section>
    </div>
{% endblock %}

courses/templates/courses/take_test.html
{% extends 'core/base.html' %}

{% block content %}
<h2>Take Test: {{ test.title }}</h2>
<form method="post">
    {% csrf_token %}
    {% for question in questions %}
    <div>
        <h4>{{ question.text|default_if_none:"Media Question" }}</h4>
        {% if question.question_type == 'IMG' and question.image %}
    <img src="{{ question.image.url }}" alt="Question Image" style="max-width: 100%;">

        {% elif question.question_type == 'AUD' and question.audio %}
            <audio controls>
                <source src="{{ question.audio.url }}" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        {% endif %}
        {% for answer in question.answers.all %}
            <label>
                {% if question.question_type == 'MC' %}
                    <input type="checkbox" name="answer_{{ question.id }}" value="{{ answer.id }}">
                {% else %}
                    <input type="radio" name="answer_{{ question.id }}" value="{{ answer.id }}">
                {% endif %}
                {{ answer.text }}
            </label><br>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit">Submit Answers</button>
</form>
{% endblock %}

courses/templates/courses/test_detail.html
<!-- test_detail.html -->
<form method="post">
    {% csrf_token %}
    <h2>Edit Test</h2>
    {{ test_form.as_p }}
    <button type="submit">Save Test</button>
</form>

<!-- Add sections for questions and answers similarly -->

courses/templates/courses/test_result.html
<!-- In templates/courses/test_result.html -->
{% extends 'core/base.html' %}

{% block content %}
<h2>Your Test Score</h2>
<p>Your score: {{ score }}%</p>
{% endblock %}